import { Product, ProductCategory, HeroBanner, GalleryMedia } from '../types';

export const OFFICIAL_WELDOR_CATEGORIES: ProductCategory[] = [
  {
    id: "cat-wel-01",
    name: "MIG / CO2 & TIG Welding Torches",
    slug: "mig-tig-welding-torches",
    description: "Heavy-duty 24KD, 36KD, PANA 350A/500A, and precision high-frequency TIG welding torches with air-cooled and water-cooled configurations.",
    iconName: "Flame",
    productCount: 4,
    featured: true,
    image: "/catalog_pages/page_4.png",
    bannerImage: "/catalog_pages/page_4.png",
    subCategories: ["24KD MIG Torches", "36KD MIG Torches", "PANA 350A/500A Torches", "TIG Welding Torches (WP-18/26)"],
    seoKeywords: ["MIG welding torch", "24KD torch", "36KD torch", "PANA 500A torch", "TIG torch", "CO2 welding torch"],
    seoMetaTitle: "MIG & TIG Industrial Welding Torches | Weldor Industries",
    seoMetaDescription: "High-performance air-cooled and water-cooled MIG & TIG welding torches manufactured by Earth Metal Industries."
  },
  {
    id: "cat-cut-02",
    name: "Plasma & Gas Cutting Torches",
    slug: "plasma-gas-cutting-torches",
    description: "Manual handheld and Automatic CNC Plasma cutting torches up to 200A and injector / equal-pressure PNME & ANME gas cutting torches up to 300mm capacity.",
    iconName: "Zap",
    productCount: 4,
    featured: true,
    image: "/catalog_pages/page_6.png",
    bannerImage: "/catalog_pages/page_7.png",
    subCategories: ["Plasma Manual Torches", "Plasma Automatic CNC Torches", "PNME Injector Gas Torches", "ANME Equal Pressure Torches"],
    seoKeywords: ["plasma torch", "CNC plasma torch", "gas cutting torch", "PNME torch", "ANME cutting torch"],
    seoMetaTitle: "Plasma & Oxy-Fuel Gas Cutting Torches | Weldor Industries",
    seoMetaDescription: "Industrial plasma and gas cutting torches for structural steel cutting up to 300mm thickness."
  },
  {
    id: "cat-reg-03",
    name: "Industrial Gas Pressure Regulators",
    slug: "gas-pressure-regulators",
    description: "Heavy-duty forged brass gas pressure regulators and flowmeters for Oxygen, Acetylene, Argon/CO2, Nitrogen, Hydrogen, and LPG.",
    iconName: "Droplets",
    productCount: 5,
    featured: true,
    image: "/catalog_pages/page_9.png",
    bannerImage: "/catalog_pages/page_9.png",
    subCategories: ["Oxygen Regulators", "Acetylene Regulators", "Argon / CO2 Flowmeters", "Nitrogen High-Pressure Regulators", "Industrial LPG Regulators"],
    seoKeywords: ["gas regulator", "oxygen regulator", "argon flowmeter", "acetylene regulator", "300 bar regulator"],
    seoMetaTitle: "Heavy-Duty Forged Brass Gas Pressure Regulators | Weldor",
    seoMetaDescription: "High-pressure forged brass gas regulators for oxy-fuel cutting, MIG/TIG shielding gas, and industrial heating."
  },
  {
    id: "cat-con-04",
    name: "Welding & Cutting Consumables",
    slug: "welding-cutting-consumables",
    description: "CuCrZr contact tips, conical MIG nozzles, gas diffusers, plasma electrodes, swirl rings, and precision CNC machined PNME/ANME cutting nozzles.",
    iconName: "Cpu",
    productCount: 3,
    featured: true,
    image: "/catalog_pages/page_10.png",
    bannerImage: "/catalog_pages/page_8.png",
    subCategories: ["MIG Contact Tips & Nozzles", "Plasma Electrodes & Nozzles", "PNME/ANME Cutting Tips", "Gas Diffusers & Insulators"],
    seoKeywords: ["MIG contact tip", "welding nozzle", "plasma electrode", "cutting nozzle", "gas diffuser"],
    seoMetaTitle: "Welding & Cutting Consumables & Spare Parts | Weldor",
    seoMetaDescription: "Precision machined copper and brass consumables for MIG, TIG, Plasma, and Oxy-Fuel torches."
  }
];

export const OFFICIAL_WELDOR_PRODUCTS: Product[] = [
  {
    id: "prod-weldor-01",
    sku: "WLD-MIG-24KD",
    name: "24KD MIG Welding Torch (250A Air-Cooled)",
    category: "MIG / CO2 & TIG Welding Torches",
    categoryId: "cat-wel-01",
    subCategory: "24KD MIG Torches",
    brand: "WELDOR",
    modelNumber: "WEL-24KD-PRO",
    tagline: "Heavy-duty ergonomic 250A MIG torch built for high-performance fabrication with smooth wire feeding.",
    description: "The 24KD MIG Welding Torch is a heavy-duty torch built for high-performance welding in industrial applications. Designed for durability and efficiency, it provides smooth wire feeding and consistent arc stability. Features an ergonomic rubber handle with ball-joint knuckle for reduced operator fatigue.",
    bulletPoints: [
      "Rated Current: 250A (CO2) / 220A (Mixed Gas) at 60% Duty Cycle.",
      "Cooling: High-efficiency Air-Cooled system with heavy copper conductor.",
      "Wire Diameter compatibility: 0.8 mm to 1.2 mm (Solid & Flux-cored).",
      "Available Cable Lengths: 3 meters, 4 meters, and 5 meters with EURO connector.",
      "Robust & ergonomic design with spring cable support for prolonged industrial usage."
    ],
    industries: ["Automotive & Sheet Metal", "General Fabrication", "Shipbuilding", "Heavy Machinery"],
    applications: ["MIG/MAG CO2 Structural Welding", "Automotive Body Fabrication", "Pipe & Tank Welding"],
    materials: ["High Conductivity Deoxidized Copper", "Heat-Resistant Silicone Rubber", "Reinforced Brass Body"],
    specifications: [
      { label: "Rated Current (CO2)", value: "250 A" },
      { label: "Rated Current (Mixed Gas)", value: "220 A" },
      { label: "Duty Cycle", value: "60%" },
      { label: "Wire Diameter", value: "0.8 - 1.2 mm" },
      { label: "Cooling Method", value: "Air-Cooled" },
      { label: "Cable Lengths", value: "3m / 4m / 5m" },
      { label: "Connection Type", value: "Universal EURO Connection" }
    ],
    featured: true,
    image: "/catalog_pages/page_4.png",
    gallery: ["/catalog_pages/page_4.png", "/catalog_pages/page_1.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 48,
    priceINR: 3850,
    certifications: ["ISO 9001:2015", "Make in India", "MSME Certified", "CE Standard"],
    minOrderQty: 2,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["24KD MIG torch", "250A welding torch", "MIG gun", "air cooled MIG torch", "Weldor 24KD"],
    status: "Active"
  },
  {
    id: "prod-weldor-02",
    sku: "WLD-MIG-36KD",
    name: "36KD Heavy-Duty MIG Welding Torch (320A High-Performance)",
    category: "MIG / CO2 & TIG Welding Torches",
    categoryId: "cat-wel-01",
    subCategory: "36KD MIG Torches",
    brand: "WELDOR",
    modelNumber: "WEL-36KD-HD",
    tagline: "Industrial heavy-duty 320A MIG welding torch with heavy copper swan neck and superior heat dissipation.",
    description: "The 36KD MIG Welding Torch is a heavy-duty torch built for high-performance welding in heavy engineering and structural fabrication. Designed for maximum durability and thermal efficiency, it ensures smooth wire feeding and continuous high-current arc stability under extreme production cycles.",
    bulletPoints: [
      "Rated Current: 320A (CO2) / 290A (Mixed Gas) at 60% Duty Cycle.",
      "Cooling: Heavy-duty Air-Cooled design with thickened insulated nozzle.",
      "Wire Diameter: 1.0 mm to 1.6 mm heavy wire capability.",
      "Cable Length: 3m, 4m, and 5m heavy-duty rubberized coax cable.",
      "High thermal conductivity copper alloy components for extended consumable lifespan."
    ],
    industries: ["Heavy Structural Steel", "Pressure Vessel Fabrication", "Railway & Infrastructure", "Automotive"],
    applications: ["Multi-Pass Structural Fillet Welds", "Thick Plate MIG Welding", "Boiler & Vessel Fabrication"],
    materials: ["Tellurium Copper Swan Neck", "High-Impact Nylon Handle", "Reinforced Outer Jacket"],
    specifications: [
      { label: "Rated Current (CO2)", value: "320 A" },
      { label: "Rated Current (Mixed Gas)", value: "290 A" },
      { label: "Duty Cycle", value: "60%" },
      { label: "Wire Diameter", value: "1.0 - 1.6 mm" },
      { label: "Cooling Method", value: "Air-Cooled" },
      { label: "Standard Connector", value: "EURO Standard" }
    ],
    featured: true,
    image: "/catalog_pages/page_4.png",
    gallery: ["/catalog_pages/page_4.png", "/catalog_pages/page_10.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 65,
    priceINR: 5200,
    certifications: ["ISO 9001:2015", "Make in India", "CE Standard"],
    minOrderQty: 2,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["36KD torch", "320A MIG gun", "heavy duty welding torch", "Weldor 36KD", "CO2 torch"],
    status: "Active"
  },
  {
    id: "prod-weldor-03",
    sku: "WLD-PANA-500",
    name: "PANA 350A / 500A Industrial MIG Welding Torch",
    category: "MIG / CO2 & TIG Welding Torches",
    categoryId: "cat-wel-01",
    subCategory: "PANA 350A/500A Torches",
    brand: "WELDOR",
    modelNumber: "WEL-PANA-500",
    tagline: "Heavy-duty Panasonic style 500A MIG torch with heavy copper conductor for continuous production lines.",
    description: "The PANA 350A/500A MIG Torch is designed for heavy-duty industrial welding applications, ensuring superior performance and longevity. Features high-purity copper conductors, heavy-duty trigger switch, and precision machined components for Panasonic and EURO standard wire feeders.",
    bulletPoints: [
      "Rated Current: 350A / 500A (CO2) for heavy fabrication lines.",
      "Duty Cycle: 60% with superior thermal heat sinking.",
      "Wire Diameter: 1.0 mm to 1.6 mm.",
      "High-Quality Copper Components for excellent electrical & thermal conductivity.",
      "Connection Type: EURO / PANASONIC compatible rear interface."
    ],
    industries: ["Automotive OEM Lines", "Heavy Crane Fabrication", "Shipbuilding", "Heavy Industrial Manufacturing"],
    applications: ["Heavy Duty Continuous Welding", "Automated Robotic Feeder Lines", "Thick Carbon Steel Welds"],
    materials: ["Electrolytic Copper Conductors", "Heavy Brass Connector", "Heat-Resistant Silicone Insulators"],
    specifications: [
      { label: "Rated Current", value: "350A / 500A (CO2)" },
      { label: "Duty Cycle", value: "60%" },
      { label: "Wire Size", value: "1.0 - 1.6 mm" },
      { label: "Cable Lengths", value: "3m, 4m, 5m" },
      { label: "Connection Interface", value: "EURO / PANASONIC" }
    ],
    featured: true,
    image: "/catalog_pages/page_5.png",
    gallery: ["/catalog_pages/page_5.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 82,
    priceINR: 6600,
    certifications: ["ISO 9001:2015", "Make in India", "MSME"],
    minOrderQty: 1,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["PANA 500A torch", "PANA 350A torch", "Panasonic MIG torch", "500A welding gun"],
    status: "Active"
  },
  {
    id: "prod-weldor-04",
    sku: "WLD-TIG-PRO",
    name: "Precision High-Frequency TIG Welding Torch (150A - 400A)",
    category: "MIG / CO2 & TIG Welding Torches",
    categoryId: "cat-wel-01",
    subCategory: "TIG Welding Torches (WP-18/26)",
    brand: "WELDOR",
    modelNumber: "WEL-TIG-WP26",
    tagline: "Ultra-precise TIG welding torch with flexible neck and silicone rubber handle for stainless steel & aluminum.",
    description: "The TIG Welding Torch is engineered for precision welding, ensuring clean and high-quality welds in stainless steel, aluminum, titanium, and exotic metals. Features a flexible torch head for hard-to-reach angles and high-temperature resistant silicone rubber handle.",
    bulletPoints: [
      "Rated Current: 150A - 400A (Air-Cooled & Water-Cooled models available).",
      "Duty Cycle: 60% at full rated capacity.",
      "Tungsten Electrode range: 1.0 mm to 4.0 mm.",
      "Flexible Torch Head: For superior control and tight corner maneuverability.",
      "High-Temperature Resistant Silicone Rubber Handle for maximum comfort and grip."
    ],
    industries: ["Aerospace & Defense", "Pharmaceutical Equipment", "Food & Dairy Processing", "Exhaust Fabrication"],
    applications: ["Sanitary Stainless Steel Piping", "Aluminum TIG Fabrication", "Precision Sheet Metal TIG"],
    materials: ["High Temp Silicone Rubber", "High-Purity Copper Core", "Alumina Gas Lens Ceramics"],
    specifications: [
      { label: "Rated Current", value: "150A - 400A" },
      { label: "Duty Cycle", value: "60%" },
      { label: "Cooling System", value: "Air-Cooled / Water-Cooled" },
      { label: "Electrode Diameter", value: "1.0 - 4.0 mm" },
      { label: "Torch Head Type", value: "Flexible / Rigid Head" }
    ],
    featured: true,
    image: "/catalog_pages/page_5.png",
    gallery: ["/catalog_pages/page_5.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 55,
    priceINR: 4400,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 1,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["TIG torch", "WP26 torch", "WP18 water cooled TIG", "stainless steel welding torch"],
    status: "Active"
  },
  {
    id: "prod-weldor-05",
    sku: "WLD-PLC-MAN-100",
    name: "Plasma Manual Handheld Cutting Torch (40A - 200A)",
    category: "Plasma & Gas Cutting Torches",
    categoryId: "cat-cut-02",
    subCategory: "Plasma Manual Torches",
    brand: "WELDOR",
    modelNumber: "WEL-CUT-100M",
    tagline: "High-speed plasma cutting torch with minimal kerf distortion and cutting capacity up to 50mm thickness.",
    description: "The Plasma Manual Torch delivers high-speed, precise cutting with minimal distortion, making it ideal for industrial metal cutting and demolition applications. Features a durable electrode and nozzle design for extended operational life and pilot arc ignition.",
    bulletPoints: [
      "Rated Current: 40A - 200A (Depending on cutting amperage setting).",
      "Cutting Capacity: Up to 50 mm steel plate thickness.",
      "Cooling: Air-Cooled & Water-Cooled models available.",
      "Durable Electrode & Nozzle Design for extended consumable life.",
      "Compatible with major industrial plasma cutting power sources."
    ],
    industries: ["Metal Demolition & Scrap", "Structural Steel Profiling", "Sheet Metal Job Shops", "Heavy Fabrication"],
    applications: ["Carbon Steel Plate Piercing & Cutting", "Stainless Steel Profiling", "Aluminum Sheet Cutting"],
    materials: ["Hafnium Insert Electrode", "High Thermal Copper Nozzle", "Reinforced Composite Handle"],
    specifications: [
      { label: "Rated Current", value: "40A - 200A" },
      { label: "Max Cutting Thickness", value: "Up to 50 mm" },
      { label: "Cooling System", value: "Air-Cooled & Water-Cooled" },
      { label: "Gas Requirement", value: "Compressed Air / Nitrogen (4.5 - 6.0 Bar)" },
      { label: "Arc Initiation", value: "High Frequency Pilot Arc" }
    ],
    featured: true,
    image: "/catalog_pages/page_6.png",
    gallery: ["/catalog_pages/page_6.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 95,
    priceINR: 7600,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 1,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["plasma cutting torch", "manual plasma torch", "50mm cutting torch", "air plasma torch"],
    status: "Active"
  },
  {
    id: "prod-weldor-06",
    sku: "WLD-PLC-CNC-200",
    name: "Plasma Automatic CNC Gantry Cutting Torch (40A - 200A)",
    category: "Plasma & Gas Cutting Torches",
    categoryId: "cat-cut-02",
    subCategory: "Plasma Automatic CNC Torches",
    brand: "WELDOR",
    modelNumber: "WEL-CNC-200A",
    tagline: "Straight-barrel CNC machine plasma torch for automated CNC cutting tables and bevel profile gantries.",
    description: "The Plasma Automatic CNC Torch delivers high-speed, precise cutting with minimal distortion, making it ideal for automated CNC metal profiling tables and robotic cutting cells. Ensures clean, perpendicular edge cuts with minimal dross.",
    bulletPoints: [
      "Rated Current: 40A - 200A for automated continuous duty.",
      "Cutting Capacity: Clean piercing and bevel cutting up to 50 mm thickness.",
      "Cooling: High-efficiency Air-Cooled & Water-Cooled straight barrel.",
      "Universal rack and mounting barrel for CNC gantry torch height controllers (THC).",
      "Compatible with major CNC Plasma cutting systems and controllers."
    ],
    industries: ["CNC Plate Cutting Centers", "Shipyards", "Wind Tower Fabrication", "Heavy Equipment"],
    applications: ["Automated CNC Profile Cutting", "Bevel Edge Preparation", "High-Volume Steel Piercing"],
    materials: ["Precision Brass Barrel", "Silver-Hafnium Electrodes", "Ceramic Shield Deflectors"],
    specifications: [
      { label: "Rated Current", value: "40A - 200A" },
      { label: "Cutting Capacity", value: "Up to 50 mm" },
      { label: "Torch Style", value: "Straight Machine CNC Barrel (180°)" },
      { label: "Duty Cycle", value: "100% at CNC Rating" }
    ],
    featured: true,
    image: "/catalog_pages/page_6.png",
    gallery: ["/catalog_pages/page_6.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 140,
    priceINR: 11200,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 1,
    standardLeadTimeDays: 3,
    inStock: true,
    seoKeywords: ["CNC plasma torch", "automatic plasma torch", "straight plasma gun", "machine plasma torch"],
    status: "Active"
  },
  {
    id: "prod-weldor-07",
    sku: "WLD-GCT-PNME",
    name: "PNME Injector Type Gas Cutting Torch (Cutting up to 300mm)",
    category: "Plasma & Gas Cutting Torches",
    categoryId: "cat-cut-02",
    subCategory: "PNME Injector Gas Torches",
    brand: "WELDOR",
    modelNumber: "WEL-GC-PNME-300",
    tagline: "Heavy-duty forged brass injector type gas cutting torch with stainless steel lever for cuts up to 300mm.",
    description: "Technology for the Welder's World. The PNME Gas Cutting Torch is an injector-pressure mixing torch engineered for high-precision oxy-fuel metal cutting up to 300mm thick steel. Features forged brass body, stainless steel cutting oxygen lever, and ergonomic grip.",
    bulletPoints: [
      "Type: Injector Type Mixing System (Pressure Type).",
      "Cutting Capacity: Up to 300 mm thick steel plate.",
      "Gas Compatibility: Oxygen-Acetylene / Oxygen-LPG.",
      "Nozzle Type: PNME Standard Solid Copper Splined Nozzles.",
      "Body Material: Heavy Forged Brass Head & Tubes with Stainless Steel Lever."
    ],
    industries: ["Ship Breaking & Demolition", "Steel Mills & Foundries", "Heavy Structural Fabrication", "Railways"],
    applications: ["Oxy-Fuel Steel Cutting", "Scrap Demolition", "Plate Edge Beveling"],
    materials: ["Drop Forged Brass Head", "Stainless Steel Oxygen Tubes", "Die-Cast Ergonomic Lever"],
    specifications: [
      { label: "Mixing Type", value: "Injector Pressure Type" },
      { label: "Max Cutting Capacity", value: "300 mm Thickness" },
      { label: "Nozzle Compatibility", value: "PNME / PNM Standard" },
      { label: "Gas Compatibility", value: "Oxygen + Acetylene" },
      { label: "Head Angle", value: "90° Standard" }
    ],
    featured: true,
    image: "/catalog_pages/page_7.png",
    gallery: ["/catalog_pages/page_7.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 38,
    priceINR: 3050,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 2,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["gas cutting torch", "PNME torch", "injector cutting torch", "oxy acetylene torch"],
    status: "Active"
  },
  {
    id: "prod-weldor-08",
    sku: "WLD-GCT-ANME",
    name: "ANME Equal Pressure Gas Cutting Torch (Oxygen-LPG / Acetylene)",
    category: "Plasma & Gas Cutting Torches",
    categoryId: "cat-cut-02",
    subCategory: "ANME Equal Pressure Torches",
    brand: "WELDOR",
    modelNumber: "WEL-GC-ANME-300",
    tagline: "Equal pressure nozzle-mixing gas cutting torch for safe, backfire-resistant cuts up to 300mm thickness.",
    description: "The ANME Gas Cutting Torch utilizes an equal-pressure nozzle mix system where oxygen and fuel gas mix directly inside the nozzle head, providing superior backfire resistance and smooth flame cutting up to 300mm plate thickness.",
    bulletPoints: [
      "Type: Equal Pressure Nozzle Mixing System.",
      "Cutting Capacity: Up to 300 mm steel plate.",
      "Gas Compatibility: Oxygen-LPG / Oxygen-Acetylene.",
      "Nozzle Type: ANME Standard Two-Piece & Solid Nozzles.",
      "Body Material: Heavy Forged Brass with Stainless Steel Lever for smooth operation."
    ],
    industries: ["Heavy Engineering", "Steel Yards", "Infrastructure Projects", "Foundries"],
    applications: ["Heavy Billet Cutting", "Structural Beam Cutting", "Foundry Riser Removal"],
    materials: ["Heavy Forged Brass", "Stainless Steel Gas Conduits"],
    specifications: [
      { label: "Mixing System", value: "Equal Pressure Nozzle Mix" },
      { label: "Cutting Capacity", value: "Up to 300 mm" },
      { label: "Gas Types", value: "Oxygen-LPG / Oxygen-Acetylene" },
      { label: "Nozzle Type", value: "ANME Standard" }
    ],
    featured: true,
    image: "/catalog_pages/page_7.png",
    gallery: ["/catalog_pages/page_7.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 42,
    priceINR: 3350,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 2,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["ANME cutting torch", "equal pressure gas torch", "LPG cutting torch", "flame cutter"],
    status: "Active"
  },
  {
    id: "prod-weldor-09",
    sku: "WLD-REG-O2-300B",
    name: "Heavy-Duty Forged Brass Oxygen Gas Regulator (300 Bar Inlet)",
    category: "Industrial Gas Pressure Regulators",
    categoryId: "cat-reg-03",
    subCategory: "Oxygen Regulators",
    brand: "WELDOR",
    modelNumber: "WEL-REG-O2",
    tagline: "300 Bar maximum inlet forged brass dual-gauge oxygen pressure regulator for gas cutting and industrial use.",
    description: "Manufactured from high-density forged brass, the Weldor Oxygen Gas Pressure Regulator handles cylinder pressures up to 300 Bar with a stable, high-flow outlet pressure up to 12 Bar. Equipped with heavy brass dual gauges, stainless steel diaphragm, and safety relief valve.",
    bulletPoints: [
      "Gas Symbol: O2 (Oxygen).",
      "Max Inlet Pressure: 300 Bar | Max Outlet Pressure: 12 Bar.",
      "Inlet Connection: 5/8\" BSP R/H (Male) standard cylinder interface.",
      "Outlet Connection: 3/8\" BSP R/H (Male) hose nipple.",
      "Applications: Industrial gas cutting, welding, healthcare, and furnace oxygen enrichment."
    ],
    industries: ["Industrial Welding & Cutting", "Steel Mills", "Hospitals & Laboratories", "Metal Fabrication"],
    applications: ["Oxy-Fuel Flame Cutting", "Oxygen Purging", "Industrial High-Flow Oxygen Lines"],
    materials: ["Drop Forged Extruded Brass Body", "Stainless Steel Diaphragm", "Brass Pressure Gauges"],
    specifications: [
      { label: "Gas Type", value: "Oxygen (O2)" },
      { label: "Max Inlet Pressure", value: "300 Bar" },
      { label: "Max Outlet Pressure", value: "12 Bar" },
      { label: "Inlet Connection", value: "5/8\" BSP R/H (Male)" },
      { label: "Outlet Connection", value: "3/8\" BSP R/H (Male)" },
      { label: "Body Material", value: "Heavy Forged Brass" }
    ],
    featured: true,
    image: "/catalog_pages/page_9.png",
    gallery: ["/catalog_pages/page_9.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 32,
    priceINR: 2550,
    certifications: ["ISO 9001:2015", "Make in India", "CE Standard"],
    minOrderQty: 2,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["oxygen regulator", "300 bar gas regulator", "O2 regulator", "Weldor oxygen regulator"],
    status: "Active"
  },
  {
    id: "prod-weldor-10",
    sku: "WLD-REG-ACET-40B",
    name: "Industrial Acetylene Gas Pressure Regulator (40 Bar DA)",
    category: "Industrial Gas Pressure Regulators",
    categoryId: "cat-reg-03",
    subCategory: "Acetylene Regulators",
    brand: "WELDOR",
    modelNumber: "WEL-REG-DA",
    tagline: "High-precision Dissolved Acetylene regulator with left-hand threads and safety burst valve.",
    description: "Specifically designed for Dissolved Acetylene (DA) cylinders, this regulator delivers exact low-pressure fuel control (up to 1.5 Bar) required for stable oxy-acetylene flame cutting and brazing without risk of fuel fluctuations.",
    bulletPoints: [
      "Gas Symbol: C2H2 (Acetylene / DA).",
      "Max Inlet Pressure: 40 Bar | Max Outlet Pressure: 1.5 Bar.",
      "Inlet Connection: 5/8\" BSP L/H (Male) reverse fuel thread.",
      "Outlet Connection: 3/8\" BSP L/H (Male) with safety flashback connection.",
      "Applications: Oxy-Acetylene welding, brazing, flame heating, and flame straightening."
    ],
    industries: ["Metal Fabrication", "Automotive Repair", "Jewelry & HVAC Brazing", "Ship Maintenance"],
    applications: ["Oxy-Acetylene Welding & Brazing", "Flame Hardening", "Demolition Torch Fuel Supply"],
    materials: ["Forged Brass Body", "Neoprene Rubber Diaphragm"],
    specifications: [
      { label: "Gas Type", value: "Acetylene (C2H2)" },
      { label: "Max Inlet Pressure", value: "40 Bar" },
      { label: "Max Outlet Pressure", value: "1.5 Bar" },
      { label: "Inlet Connection", value: "5/8\" BSP L/H (Male)" },
      { label: "Outlet Connection", value: "3/8\" BSP L/H (Male)" }
    ],
    featured: true,
    image: "/catalog_pages/page_9.png",
    gallery: ["/catalog_pages/page_9.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 34,
    priceINR: 2700,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 2,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["acetylene regulator", "DA regulator", "gas cutting regulator", "Weldor acetylene"],
    status: "Active"
  },
  {
    id: "prod-weldor-11",
    sku: "WLD-REG-AR-CO2",
    name: "Argon / CO2 Shielding Gas Regulator & Flowmeter (300 Bar)",
    category: "Industrial Gas Pressure Regulators",
    categoryId: "cat-reg-03",
    subCategory: "Argon / CO2 Flowmeters",
    brand: "WELDOR",
    modelNumber: "WEL-FLW-AR200",
    tagline: "Precision calibrated flowmeter tube regulator for MIG/TIG shielding gas flow control up to 25 L/min.",
    description: "Essential for high-quality TIG and MIG/MAG welding, this dual-function regulator features a cylinder pressure gauge and a polycarbonate flow tube calibrated for Argon and CO2 flow rates between 0 and 25 LPM. Ensures zero porosity and optimum shielding arc envelope.",
    bulletPoints: [
      "Gas Symbol: Ar / CO2 (Argon / Carbon Dioxide).",
      "Max Inlet Pressure: 200 - 300 Bar | Outlet Flow: 0 - 25 Litres/min (2 - 4 Bar).",
      "Inlet Connection: 5/8\" BSP R/H (Male) or 0.860\" x 14 TPI (Female) for CO2.",
      "High impact transparent polycarbonate flow tube with stainless steel indicator ball.",
      "Applications: TIG welding & shielding gas control, MIG/MAG automated welding."
    ],
    industries: ["TIG Pipe Welding", "Automotive Body Fabrication", "Aerospace Manufacturing", "Robotic Welding Cells"],
    applications: ["TIG Shielding Gas Regulation", "CO2 MIG Welding Flow Control", "Purging Gas Backing"],
    materials: ["Forged Brass Body", "Polycarbonate Flowmeter Tube", "Stainless Steel Float Ball"],
    specifications: [
      { label: "Gas Types", value: "Argon (Ar) / Carbon Dioxide (CO2)" },
      { label: "Max Inlet Pressure", value: "300 Bar" },
      { label: "Flow Rate", value: "0 - 25 L/min" },
      { label: "Inlet Connection", value: "5/8\" BSP R/H (Male)" },
      { label: "Outlet Connection", value: "3/8\" BSP R/H (Male)" }
    ],
    featured: true,
    image: "/catalog_pages/page_9.png",
    gallery: ["/catalog_pages/page_9.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 36,
    priceINR: 2900,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 2,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["argon flowmeter", "CO2 flowmeter regulator", "TIG regulator", "MIG gas flowmeter"],
    status: "Active"
  },
  {
    id: "prod-weldor-12",
    sku: "WLD-REG-LPG-17B",
    name: "Industrial Heavy-Duty Forged Brass LPG Regulator (17 Bar Inlet)",
    category: "Industrial Gas Pressure Regulators",
    categoryId: "cat-reg-03",
    subCategory: "Industrial LPG Regulators",
    brand: "WELDOR",
    modelNumber: "WEL-REG-LPG",
    tagline: "Adjustable knob forged brass LPG regulator for high-intensity industrial heating, brazing & burners.",
    description: "High-flow industrial Liquefied Petroleum Gas (LPG) regulator with adjustable outlet pressure (0-4 Bar or 0-10 Bar). Engineered with a heavy-duty forged brass body for industrial heating torches, commercial furnaces, flame brazing, and asphalt heating.",
    bulletPoints: [
      "Gas Type: Liquefied Petroleum Gas (LPG).",
      "Inlet Pressure: Up to 17 Bar | Outlet Pressure: 0-4 Bar / 0-10 Bar (Adjustable Knob).",
      "Material: Heavy-Duty Forged Brass Body.",
      "Inlet Connection: Standard POL / 5/8\" BSP L/H female cylinder connection.",
      "Applications: Industrial heating, welding & cutting, brazing, soldering & commercial LPG systems."
    ],
    industries: ["Industrial Heat Treatment", "Roofing & Asphalt Heating", "Commercial Kitchens & Burners", "Brazing"],
    applications: ["Heavy Preheating Torches", "Copper Pipe Flame Brazing", "Industrial Burner Gas Supply"],
    materials: ["Drop Forged Brass", "Reinforced Synthetic Diaphragm"],
    specifications: [
      { label: "Gas Type", value: "LPG" },
      { label: "Inlet Pressure", value: "Up to 17 Bar" },
      { label: "Outlet Pressure", value: "0 - 4 Bar / 0 - 10 Bar (Adjustable)" },
      { label: "Body Material", value: "Heavy-Duty Forged Brass" }
    ],
    featured: false,
    image: "/catalog_pages/page_9.png",
    gallery: ["/catalog_pages/page_9.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 28,
    priceINR: 2250,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 2,
    standardLeadTimeDays: 2,
    inStock: true,
    seoKeywords: ["LPG regulator", "industrial gas regulator", "brass LPG regulator", "heating torch regulator"],
    status: "Active"
  },
  {
    id: "prod-weldor-13",
    sku: "WLD-CON-MIG-KIT",
    name: "MIG Welding Consumables Kit (Contact Tips, Nozzles, Diffusers)",
    category: "Welding & Cutting Consumables",
    categoryId: "cat-con-04",
    subCategory: "MIG Contact Tips & Nozzles",
    brand: "WELDOR",
    modelNumber: "WEL-MIG-KIT-24-36",
    tagline: "CuCrZr heavy-duty contact tips and conical gas nozzles for 24KD, 36KD and 500A MIG torches.",
    description: "Comprehensive assortment of premium MIG consumables including Copper-Chromium-Zirconium (CuCrZr) contact tips (0.8mm, 1.0mm, 1.2mm, 1.6mm), nickel-plated conical gas nozzles, brass gas diffusers, and torch swan necks for maximum arc life.",
    bulletPoints: [
      "CuCrZr Contact Tips provide 3x longer operational life compared to standard E-Cu copper tips.",
      "Precision CNC drilled bore holes ensure zero wire binding and reduced micro-arcing.",
      "Nickel-plated outer nozzles resist spatter buildup and thermal distortion.",
      "Complete range for 15AK, 24KD, 25AK, 36KD, 501D, and PANA 350A/500A torches.",
      "Supplied in bulk packs of 10, 50, and 100 pieces."
    ],
    industries: ["All Industrial Fabrication", "Automotive Body Shops", "Robotic Welding Facilities"],
    applications: ["Daily MIG Welding Consumable Replacement", "Spatter Resistance Maintenance"],
    materials: ["CuCrZr Copper Alloy", "Brass Gas Diffuser", "Ceramic Insulator"],
    specifications: [
      { label: "Tip Sizes", value: "0.8mm, 1.0mm, 1.2mm, 1.6mm" },
      { label: "Thread Size", value: "M6 / M8 Standard" },
      { label: "Nozzle Type", value: "Conical / Cylindrical" },
      { label: "Material Grade", value: "CuCrZr Copper" }
    ],
    featured: true,
    image: "/catalog_pages/page_10.png",
    gallery: ["/catalog_pages/page_10.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 15,
    priceINR: 1200,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 5,
    standardLeadTimeDays: 1,
    inStock: true,
    seoKeywords: ["MIG contact tip", "24KD nozzle", "36KD tip", "welding diffuser", "M6 contact tip"],
    status: "Active"
  },
  {
    id: "prod-weldor-14",
    sku: "WLD-CON-PL-KIT",
    name: "Plasma Cutting Consumables Set (Hafnium Electrodes & Nozzles)",
    category: "Welding & Cutting Consumables",
    categoryId: "cat-con-04",
    subCategory: "Plasma Electrodes & Nozzles",
    brand: "WELDOR",
    modelNumber: "WEL-PL-CON-100",
    tagline: "Pure hafnium insert electrodes and precision swirl rings for clean, high-speed plasma arc cutting.",
    description: "High-durability plasma cutting replacement set featuring pure hafnium core electrodes, tellurium copper cutting nozzles (1.1mm, 1.3mm, 1.5mm, 1.7mm), ceramic swirl rings, and retaining shield caps for handheld and CNC plasma torches.",
    bulletPoints: [
      "Pure Hafnium Core Inserts for fast, high-temperature pilot arc initiation.",
      "Precision CNC Machined Tellurium Copper Orifices for narrow kerf width.",
      "High heat-resistant ceramic swirl rings for stable swirling plasma gas column.",
      "Extended lifespan: Over 300+ piercing cycles per electrode.",
      "Compatible with 40A, 60A, 80A, 100A, 120A, and 200A plasma torches."
    ],
    industries: ["Plasma Profiling Shops", "Shipyards", "Sheet Metal Fabrication", "Demolition"],
    applications: ["Plasma Cutting Consumable Spares", "CNC Torch Replacement"],
    materials: ["Tellurium Copper", "Pure Hafnium", "Industrial Alumina Ceramic"],
    specifications: [
      { label: "Electrode Core", value: "Pure Hafnium (Hf)" },
      { label: "Nozzle Orifice Sizes", value: "1.1mm, 1.3mm, 1.5mm, 1.7mm, 2.0mm" },
      { label: "Amperage Range", value: "40A - 200A" }
    ],
    featured: false,
    image: "/catalog_pages/page_8.png",
    gallery: ["/catalog_pages/page_8.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 18,
    priceINR: 1450,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 5,
    standardLeadTimeDays: 1,
    inStock: true,
    seoKeywords: ["plasma electrode", "plasma nozzle", "plasma swirl ring", "hafnium electrode"],
    status: "Active"
  },
  {
    id: "prod-weldor-15",
    sku: "WLD-NOZ-PNME",
    name: "PNME & ANME Gas Cutting Nozzles (1/32\" to 1/8\" CNC Machined)",
    category: "Welding & Cutting Consumables",
    categoryId: "cat-con-04",
    subCategory: "PNME/ANME Cutting Tips",
    brand: "WELDOR",
    modelNumber: "WEL-NOZ-116",
    tagline: "Solid drawn copper outer nozzles with brass splines for clean, square oxy-fuel cuts up to 300mm.",
    description: "Precision CNC turned PNME and ANME gas cutting nozzles. Solid drawn copper outer sleeve provides maximum heat dissipation, while inner brass splined core ensures uniform preheat flame envelope and laminar cutting oxygen stream.",
    bulletPoints: [
      "Available Sizes: 1/32\", 3/64\", 1/16\", 5/64\", 3/32\", 1/8\" (Cuts 3mm to 300mm steel).",
      "PNME for Oxygen-LPG / Propane gas; ANME for Oxygen-Acetylene.",
      "100% flame and leak tested at factory before dispatch.",
      "Resistant to high radiant heat and slag sticking.",
      "Provides smooth, square cut edges with minimal post-cut grinding required."
    ],
    industries: ["Steel Service Centers", "Heavy Fabrication", "Foundries", "Scrap Yards"],
    applications: ["Oxy-Fuel Manual Torch Cutting", "Automated Pug Cutting Machine"],
    materials: ["Deoxidized Solid Copper", "Free Cutting Brass Spline"],
    specifications: [
      { label: "Nozzle Type", value: "PNME / ANME" },
      { label: "Standard Sizes", value: "1/32\", 3/64\", 1/16\", 5/64\", 3/32\", 1/8\"" },
      { label: "Cutting Plate Range", value: "3 mm - 300 mm" }
    ],
    featured: false,
    image: "/catalog_pages/page_8.png",
    gallery: ["/catalog_pages/page_8.png"],
    catalogPdfUrl: "/catalog/Weldor_Welding_Product_Catalog.pdf",
    priceUSD: 6,
    priceINR: 480,
    certifications: ["ISO 9001:2015", "Make in India"],
    minOrderQty: 10,
    standardLeadTimeDays: 1,
    inStock: true,
    seoKeywords: ["PNME nozzle", "ANME cutting nozzle", "gas cutting tip", "oxy fuel tip"],
    status: "Active"
  }
];

export const OFFICIAL_WELDOR_BANNERS: HeroBanner[] = [
  {
    id: "ban-weldor-01",
    badge: "EARTH METAL INDUSTRIES — WELDOR BRAND",
    title: "Precision In Every Spark.",
    highlightText: "High-Performance MIG, TIG & Plasma Cutting Torches.",
    subtitle: "ISO 9001:2015 Certified OEM & Global Exporter | Make in India",
    description: "Manufactured at our Jamnagar engineering plant, Weldor delivers heavy-duty 24KD/36KD MIG torches, 700 Bar & 300 Bar gas pressure regulators, and precision CNC cutting torches.",
    bgImageUrl: "/catalog_pages/page_1.png",
    productImageUrl: "/catalog_pages/page_4.png",
    productSku: "WLD-MIG-36KD",
    productName: "36KD Heavy-Duty MIG Welding Torch (320A)",
    transitionEffect: "zoom",
    overlayTheme: "dark-glass",
    primaryBtnText: "Explore Welding Catalog",
    primaryBtnAction: "public-products",
    secondaryBtnText: "Download PDF Catalog",
    secondaryBtnAction: "public-rfq",
    stats: [
      { label: "Cutting Capacity", value: "Up to 300mm" },
      { label: "Max Pressure", value: "300 Bar" },
      { label: "Export Quality", value: "100% Tested" }
    ],
    features: ["100% Leak & Arc Tested", "Heavy Forged Brass Construction", "Direct Factory Pricing"],
    active: true,
    displayOrder: 1,
    autoplayDurationSec: 6
  },
  {
    id: "ban-weldor-02",
    badge: "FORGED BRASS INDUSTRIAL REGULATORS",
    title: "300 Bar High-Pressure Gas Regulators.",
    highlightText: "Engineered for Extreme Safety & Precision Flow.",
    subtitle: "Oxygen, Acetylene, Argon/CO2 Flowmeters, Nitrogen & LPG",
    description: "Heavy forged brass dual-gauge gas pressure regulators with stainless steel diaphragms designed for heavy industrial cutting, TIG shielding, and heating applications.",
    bgImageUrl: "/catalog_pages/page_9.png",
    productImageUrl: "/catalog_pages/page_9.png",
    productSku: "WLD-REG-O2-300B",
    productName: "Forged Brass Oxygen Regulator (300 Bar)",
    transitionEffect: "kenburns",
    overlayTheme: "orange-tech",
    primaryBtnText: "View Gas Regulators",
    primaryBtnAction: "public-products",
    secondaryBtnText: "Request Price Quotation",
    secondaryBtnAction: "public-rfq",
    stats: [
      { label: "Inlet Rating", value: "300 Bar" },
      { label: "Body Material", value: "Forged Brass" },
      { label: "Standard", value: "BSPP / IS" }
    ],
    features: ["Dual Heavy Gauges", "Safety Relief Valve Built-in", "Zero Pressure Fluctuation"],
    active: true,
    displayOrder: 2,
    autoplayDurationSec: 6
  }
];

export const OFFICIAL_WELDOR_GALLERY: GalleryMedia[] = [
  {
    id: "gal-01",
    title: "MIG / CO2 Torches Range - 24KD & 36KD",
    category: "Product Closeups",
    type: "Photo",
    mediaTypeGroup: "photo",
    url: "/catalog_pages/page_4.png",
    thumbnail: "/catalog_pages/page_4.png",
    caption: "Official Weldor 24KD and 36KD ergonomic air-cooled MIG welding torches with euro connectors.",
    tags: ["MIG Torches", "24KD", "36KD", "Weldor Catalog"],
    createdAt: "2026-09-25"
  },
  {
    id: "gal-02",
    title: "Heavy-Duty PANA 350A & 500A Torches",
    category: "Product Closeups",
    type: "Photo",
    mediaTypeGroup: "photo",
    url: "/catalog_pages/page_5.png",
    thumbnail: "/catalog_pages/page_5.png",
    caption: "Heavy-duty Panasonic style 350A and 500A CO2 / MAG welding torches.",
    tags: ["PANA 500A", "Heavy Welding", "Weldor Catalog"],
    createdAt: "2026-09-25"
  },
  {
    id: "gal-03",
    title: "Plasma & Oxy-Fuel Cutting Torch Lineup",
    category: "Product Closeups",
    type: "Photo",
    mediaTypeGroup: "photo",
    url: "/catalog_pages/page_6.png",
    thumbnail: "/catalog_pages/page_6.png",
    caption: "Industrial plasma manual and CNC automatic cutting torches with PNME/ANME gas cutting torches.",
    tags: ["Plasma Torch", "Gas Cutting", "Weldor Catalog"],
    createdAt: "2026-09-25"
  },
  {
    id: "gal-04",
    title: "Forged Brass Industrial Gas Regulators",
    category: "Testing Bays",
    type: "Photo",
    mediaTypeGroup: "photo",
    url: "/catalog_pages/page_9.png",
    thumbnail: "/catalog_pages/page_9.png",
    caption: "300 Bar Oxygen, DA Acetylene, Argon/CO2 Flowmeter and Nitrogen regulators.",
    tags: ["Gas Regulators", "300 Bar", "Oxygen", "Flowmeter"],
    createdAt: "2026-09-25"
  },
  {
    id: "gal-05",
    title: "CuCrZr Contact Tips & Nozzle Consumables",
    category: "CNC Machining",
    type: "Photo",
    mediaTypeGroup: "photo",
    url: "/catalog_pages/page_10.png",
    thumbnail: "/catalog_pages/page_10.png",
    caption: "Precision CNC turned copper contact tips, gas nozzles, and diffusers.",
    tags: ["Consumables", "Contact Tips", "CNC Brass"],
    createdAt: "2026-09-25"
  },
  {
    id: "gal-06",
    title: "Hafnium Plasma Electrodes & CNC Cutting Tips",
    category: "Factory Floor",
    type: "Photo",
    mediaTypeGroup: "photo",
    url: "/catalog_pages/page_11.png",
    thumbnail: "/catalog_pages/page_11.png",
    caption: "Premium hafnium core plasma electrodes and PNME/ANME three-seat cutting nozzles.",
    tags: ["Plasma Electrodes", "PNME Tips", "Factory Production"],
    createdAt: "2026-09-25"
  }
];

