import type { Role } from '../types';

export const INITIAL_ROLES: Role[] = [
  {
    id: 'role-super-admin',
    name: 'Super Admin',
    description: 'Full system access across public site, CMS, CRM, HRMS, Payroll, security, RBAC, and integrations.',
    isSystem: true,
    scope: 'All',
    permissions: [
      { module: 'dashboard', actions: ['view', 'create', 'edit', 'delete', 'assign', 'reassign', 'approve', 'export', 'import', 'publish', 'send', 'configure'] },
      { module: 'leads', actions: ['view', 'create', 'edit', 'delete', 'assign', 'reassign', 'approve', 'export', 'import', 'send', 'configure'] },
      { module: 'companies', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { module: 'contacts', actions: ['view', 'create', 'edit', 'delete', 'export'] },
      { module: 'products', actions: ['view', 'create', 'edit', 'delete', 'publish', 'configure'] },
      { module: 'rfqs', actions: ['view', 'create', 'edit', 'assign', 'export'] },
      { module: 'samples', actions: ['view', 'create', 'edit', 'approve', 'send'] },
      { module: 'quotations', actions: ['view', 'create', 'edit', 'approve', 'send', 'export'] },
      { module: 'trials', actions: ['view', 'create', 'edit', 'approve'] },
      { module: 'orders', actions: ['view', 'create', 'edit', 'approve', 'export'] },
      { module: 'employees', actions: ['view', 'create', 'edit', 'delete', 'approve', 'export', 'configure'] },
      { module: 'payroll', actions: ['view', 'create', 'edit', 'delete', 'approve', 'send', 'export', 'configure'] },
      { module: 'attendance', actions: ['view', 'create', 'edit', 'approve', 'export'] },
      { module: 'exhibitions', actions: ['view', 'create', 'edit', 'publish', 'configure'] },
      { module: 'cms', actions: ['view', 'create', 'edit', 'publish', 'configure'] },
      { module: 'rbac', actions: ['view', 'create', 'edit', 'delete', 'assign', 'configure'] },
      { module: 'analytics', actions: ['view', 'export'] },
      { module: 'audit', actions: ['view', 'export'] },
      { module: 'settings', actions: ['view', 'edit', 'configure'] },
    ],
  },
  {
    id: 'role-sales-manager',
    name: 'Sales Manager',
    description: 'Manages team leads, quotation approvals, pipeline targets, and performance reports.',
    isSystem: true,
    scope: 'Team',
    permissions: [
      { module: 'dashboard', actions: ['view', 'export'] },
      { module: 'leads', actions: ['view', 'create', 'edit', 'assign', 'reassign', 'export'] },
      { module: 'companies', actions: ['view', 'create', 'edit'] },
      { module: 'contacts', actions: ['view', 'create', 'edit'] },
      { module: 'products', actions: ['view'] },
      { module: 'rfqs', actions: ['view', 'create', 'edit', 'assign'] },
      { module: 'samples', actions: ['view', 'create', 'edit', 'approve'] },
      { module: 'quotations', actions: ['view', 'create', 'edit', 'approve', 'send', 'export'] },
      { module: 'trials', actions: ['view', 'create', 'edit'] },
      { module: 'orders', actions: ['view', 'create', 'edit', 'approve'] },
      { module: 'analytics', actions: ['view'] },
    ],
  },
  {
    id: 'role-hr-manager',
    name: 'HR & Payroll Manager',
    description: 'Manages employee directory, biometric attendance, salary generation, and compliance.',
    isSystem: true,
    scope: 'All',
    permissions: [
      { module: 'dashboard', actions: ['view'] },
      { module: 'employees', actions: ['view', 'create', 'edit', 'delete', 'approve', 'export', 'configure'] },
      { module: 'payroll', actions: ['view', 'create', 'edit', 'approve', 'send', 'export', 'configure'] },
      { module: 'attendance', actions: ['view', 'create', 'edit', 'approve', 'export'] },
      { module: 'audit', actions: ['view'] },
    ],
  },
];
